### ISSUE TITLE
where is "more info" button ?

### ISSUE THREAD

**Issue by remil023** [mapsme/api-android#21]
Please help me guys, i read this line :

> MapsWithMe will send back to your application when user press "More Info" button

I already install Maps.Me application from google play store, but when i open it, and select some point, i can't find **More Info** button.

Anybody got the same issue, or is it just me.

Thank You

**Comment by Jmaguerre** [comment]
Hello @remil023, the button changed. The last version showed a 'Back' button instead but anyways with last week update the api calls are broken and nothing appears on the map. Sad 😢

**Comment by burivuh** [comment]
Please try 6.3.7 in the upcoming days

**Comment by amitsadafule** [comment]
Hi. I have installed 6.3.7 version of maps.me but "More Info" is still not shown. Is there any particular configuration need to be done (other than sending pendingIntent) for showing this button (or option)?

**Comment by amitsadafule** [comment]
From other threads I found that, for some reasons, "More Info" button is not now shown and same action is performed on "Back" button, after clicking on point. Also instead of sending point id directly, it is giving uri in which id is present. We need to extract the id from that uri for our use. Thanks to https://github.com/cgeo/cgeo/issues/5916

**Comment by remil023** [comment]
Thank you guys for this info, i will try it soon
